pipeline {
    agent any

    options {
        skipDefaultCheckout true
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir ('ClientAngular/server') {
                	sh 'docker-compose build'
                }                                
            }
        }
        stage('Deploy') {
            steps {
                dir ('ClientAngular/server') {
                	sh 'docker-compose down --remove-orphans'
                    sh 'docker-compose up -d --build'
                }
                
            }
        }
    }
}
